/**
 * POS Receipt System API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Product { 
    id?: number;
    name?: string;
    price?: number;
    /**
     * Central GST rate (%)
     */
    cgstRate?: number;
    /**
     * State GST rate (%)
     */
    sgstRate?: number;
    description?: string;
}

