/**
 * POS Receipt System API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductsPostRequest { 
    name?: string;
    price?: number;
    taxRate?: number;
    description?: string;
}

