/**
 * POS Receipt System API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SalesPostRequestItemsInner } from './salesPostRequestItemsInner';


export interface SalesPostRequest { 
    items?: Array<SalesPostRequestItemsInner>;
}

