/**
 * POS Receipt System API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SaleItemsInner { 
    productId?: number;
    quantity?: number;
    unitPrice?: number;
    taxRate?: number;
    taxAmount?: number;
    lineTotal?: number;
}

