/**
 * POS Receipt System API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SaleItemsInner } from './saleItemsInner';


export interface Sale { 
    id?: number;
    items?: Array<SaleItemsInner>;
    subtotal?: number;
    taxTotal?: number;
    grandTotal?: number;
    createdAt?: string;
}

