/**
 * POS Receipt System API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SaleItemsInner { 
    productId?: number;
    quantity?: number;
    unitPrice?: number;
    /**
     * Central GST rate (%)
     */
    cgstRate?: number;
    /**
     * State GST rate (%)
     */
    sgstRate?: number;
    cgstAmount?: number;
    sgstAmount?: number;
    lineTotal?: number;
    subtotal?: number;
    cgstTotal?: number;
    sgstTotal?: number;
    taxTotal?: number;
    grandTotal?: number;
    createdAt?: string;
}

