/**
 * POS Receipt System API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Settings { 
    businessName?: string;
    address?: string;
    phone?: string;
    email?: string;
    defaultTaxRate?: number;
}

